spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/sys?autoReconnect=true"
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    web:
      pageable:
        default-page-size: 20
  jpa:
    hibernate:
      ddl-auto: update

    generate-ddl: true

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500

    open-in-view: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  mvc:
    hiddenmethod:
      filter:
        enabled: true


  profiles:
    include: jwt